# Generated by Django 4.0.5 on 2022-06-26 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
