# Generated by Django 4.0.5 on 2022-06-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_basket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
