# Generated by Django 4.0.5 on 2022-06-27 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_remove_book_qty_basket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
