# Generated by Django 4.0.5 on 2022-09-12 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_book_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='qty',
        ),
    ]
